### ISSUE TITLE
You up?

### ISSUE THREAD

**Issue by WrightZAW** [BergEB/proto-bengt#3]

**Comment by NewellML** [comment]
Where you at?

**Comment by WrightZAW** [comment]
Status: missin you rn
![F1648E07-A92F-4613-AD43-E32EC2143554](https://user-images.githubusercontent.com/43044204/69081239-2e86fe80-0a03-11ea-9cb8-fe4c016a01ef.jpeg)

**Comment by NewellML** [comment]
![09949691-0C6A-488E-A313-5669F082EA15](https://user-images.githubusercontent.com/43044186/69081374-70b04000-0a03-11ea-978b-94c2dda7e2b9.jpeg)

**Comment by NewellML** [comment]
I’m afraid the robarazzi is coming for you


RUN!!

**Comment by GertonsonC** [comment]
Hey pals! I really hope you’re having a great time in your Advanced Computer Science course! Pictured below is my good pal Robert De Niro, he played Murray Franklin in the 2019 film “Joker”. Fun fact: he introduced Arthur Fleck as the Joker due to his request.
![1190427F-C032-4CA4-ACEC-BE9D86F45B82](https://user-images.githubusercontent.com/31768160/69081404-8887c400-0a03-11ea-9aa9-28e22d5971b1.jpeg)

**Comment by Decimation** [comment]
Hey do any of you guys know this **[REDACTED]**? He stole all of my shekels. It greatly upset me.

![IMG_20190617_185703-04-01](https://user-images.githubusercontent.com/4624891/76803250-65013a00-67a7-11ea-9d0e-9eab81ccc60d.jpeg)

Robert

Sent from my R̠̦̗̟̜̖̝̥̦͖̙̺̓̽̾ͧ̏ͪͮͭ̏ͪ̏ͧͫ́͘ͅȨ̴̵̻̬̗̠͕͕̘̤̮̼̮̪̇̾ͮ̒͜͞ͅI̡̦̙̮̲̣̪̰̻̞͕͎͉̅́̑̈͆̑͒͆ͣͤ́̚N̢͖̤̼͍̣͙͇͈̫͖̦̙̲̼͊̌͋͑̍̒͑̂͘͡A̧̛̛̪̖̝͔̝̠̭͇̦͎͙̲͂ͮ̌ͨ͂ͧ́͟Rͮͣ̊ͭ͋͋̓͋̇ͦ̋̆̉͏̱̰̱͙̥̱̭͖͞͡T̷̨͈̬̠͓͚̱͔̝̆̋̎̊͐̾̇ͦ̿̌̑̇͛́͘̕Z͒ͨͥ̾̀̈́̾͏̸̤̪̤̻̀͢͝_̶̹͈͔͖̩̣̅ͥ̽ͬ͛̍̑̕͠͡D̴͍̝̫̝̓̏ͨ̑̈ͣ̔̿͑̄̍͒ͯ͑ͪ̿̾̾̀͝͡Ḛ̴̡͓͓̭͎̜̣͇̤͎̰̲͖̺̄̓͊̆̎ͤ̑ͤͯ̿ͧ̉̆̍̅̃́ͦV̟̱̘̗͓̘̳̰̞͍ͤ̌̋ͥͨͯ̊̽̀͋̑̕͡I͑̊̃ͫ̓̅ͣ̏̋̽̽̔͐̚҉̴̛̹͈̱̜̪̻͚̞̺̩̰̱̲̰͖͔̭͟͞C̨̡̡̥̝̭̙̗̼̫͎̯̥ͯ̆̒͐̑̈́̈́ͨ̑͆͂̉̈ͬ̋̎́Ḛ̛̝͈̮͈͔̣̺̬̟̙̲̱̳̞̭̖̮̉͂ͫ̕͟͝͝
